version: "2"
services:
    vming:
        image: lbbniu/nginx
        ports:
            - "80:80"
            - "443:443"
        #entrypoint: ["nginx"]
        links:
            - php7:php7.vming.net
        restart: always
        labels:
            aliyun.probe.url: http://container/
            aliyun.scale: '3' 

    php7:
        restart: always
        image: lbbniu/php7
        ports:
            - "9000:9000"
        labels:
            aliyun.probe.url: tcp://container:9000/
            aliyun.scale: '3'